version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - /Applications/MAMP/htdocs/dev/docker/env_web_esgi/appli1/code:/code
            - /Applications/MAMP/htdocs/dev/docker/env_web_esgi/appli1/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - /Applications/MAMP/htdocs/dev/docker/env_web_esgi/appli1/code:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
